import 'package:csh_annotation/annotation.dart';

enum ComponentGroup with AbsComponentGroup {
  shipexHomeComponentKey("Shipex Home"),
  shipexGeneralHeaderComponentKey("Shipex General Header"),
  disputedImageCaptureComponentKey("Disputed Image Capture"),
  disputedImageBarcodeScannerComponentKey("Disputed Image Barcode Scanner"),
  calculatorMediaCaptureComponentKey("Calculator Media Capture"),
  auditBarcodeScannedComponentKey("Audit Barcode Scanner"),
  auditQuestionComponentKey("Audit Question"),
  auditQuestionSummaryComponentKey("Audit Question Summary"),
  barcodeScannerComponentKey("Barcode Qc"),
  disputedQuestionsComponentKey("Disputed Questions"),
  calculatorComponentKey("Calculator"),
  deviceReceiveComponentKey("Device Receive"),
  qcGeneralHeaderComponentKey("QC General Header"),
  qcActionComponentKey("QC Action"),
  loginComponentKey("Login"),
  trcAndQcLoginComponentKey("Trc and QC Login"),
  pendingPartDetailsComponentKey("Pending Part Details"),
  pendingDeliveryComponentKey("Pending Delivery"),
  alternatePartComponentKey("Alternate Part"),
  assignedPartDetailsComponentKey("Assigned Part Details Component"),
  assignPartBarcodeScannerComponentKey("Assign Part Barcode Scanner"),
  assignedDeviceDetailsComponentKey("Assigned device Details"),
  inventoryHomeComponentKey("Inventory Home"),
  pendingPartListComponentKey("Pending Part List"),
  returnItemStatusComponentKey("Return Item Status"),
  returnComponentKey("Return"),
  summaryComponentKey("Summary"),
  partSelectionQCComponentKey("Part Selection QC"),
  elssStatusComponentKey("Elss Status"),
  allowedOptionComponentKey("Allowed Options"),
  addPartsQcComponentKey("Add Parts QC"),
  partSelectionComponentKey("Part Selection TRC"),
  brandDetailsListingComponentKey("Brand Details Listing"),
  addPartComponentKey("ADD Part"),
  addDeviceMediaComponentKey("Add Device Media"),
  elssHomeComponentKey("Elss Home"),
  managePartsComponentKey("Manage Parts"),
  myDevicesComponentKey("My Devices"),
  wipDeviceComponentKey("WIP Devices"),
  viewReportComponentKey("View Report"),
  engineerHomeComponentKey("Engineer Home"),
  homeComponentKey("Home"),
  l4ComponentKey("L4"),
  pqStatusChangeComponentKey("PQ Status Change"),
  partQcHomeComponentKey("Part Qc Home"),
  deliveryDeliverEngineerPartsComponentKey("Delivery Deliver Engineer Parts"),
  pickUpReceiveEngineerPartsCompo("PickUp Receive Engineer Parts"),
  riderHomeComponentKey("Rider Home"),
  receiveRubbingDeviceComponentKey("Receive rubbing Device"),
  rubbingHomeComponentKey("Rubbing Home"),
  deviceScannerComponentKey("Device Scanner"),
  TRCExecutiveComponentKey("Trc executive"),
  generalHeaderComponentKey("General Header"),
  splashComponentKey("Splash");

  @override
  final String value;

  const ComponentGroup(this.value);
}

enum PageGroup with AbsPageGroup {
  shipexHomePageKey("Shipex Home"),
  disputedImageCapturePageKey("Disputed Image Capture"),
  disputedImageBarcodeScannerPageKey("Disputed Image Barcode Scanner"),
  calculatorMediaCapturePageKey("Calculator Media Capture"),
  auditBarcodeScannedPageKey("Audit Barcode Scanner"),
  auditQuestionPageKey("Audit Question"),
  auditQuestionSummaryPageKey("Audit Question Summary"),
  barcodeScannerPageKey("Barcode Qc"),
  disputedQuestionsPageKey("Disputed Questions"),
  calculatorPageKey("Calculator"),
  deviceReceivePageKey("Device Receive"),
  qcActionPageKey("QC Action"),
  loginPageKey("Login"),
  trcAndQcLoginPageKey("Trc and QC Login"),
  pendingPartDetailsPageKey("Pending Part Details"),
  pendingDeliveryPageKey("Pending Delivery"),
  alternatePartPageKey("Alternate Part"),
  assignedPartDetailsPageKey("Assigned Part Details Component"),
  assignPartBarcodeScannerPageKey("Assign Part Barcode Scanner"),
  assignedDeviceDetailsPageKey("Assigned device Details"),
  inventoryHomePageKey("Inventory Home"),
  pendingPartListPageKey("Pending Part List"),
  returnItemStatusPageKey("Return Item Status"),
  returnPageKey("Return"),
  summaryPageKey("Summary"),
  partSelectionQCPageKey("Part Selection QC"),
  elssStatusPageKey("Elss Status"),
  allowedOptionPageKey("Allowed Options"),
  addPartsQCPageKey("Add Parts QC"),
  partSelectionPageKey("Part Selection TRC"),
  brandDetailsListingPageKey("Brand Details Listing"),
  addPartPageKey("Add Part"),
  addDeviceMediaPageKey("Add Device Media"),
  elssHomePageKey("Elss Home"),
  managePartsPageKey("Manage Parts"),
  myDevicesPageKey("My Devices"),
  wipDevicesPageKey("WIP Devices"),
  viewReportPageKey("View Report"),
  engineerHomePageKey("Engineer Home"),
  homePageKey("Home"),
  l4PageKey("L4"),
  pqStatusChangePageKey("PQ Status Change"),
  partQcHomePageKey("Part Qc Home"),
  deliveryDeliverEngineerPartsPageKey("Delivery Deliver Engineer Parts"),
  pickUpReceiveEngineerPageKey("PickUp Receive Engineer Parts"),
  riderHomePageKey("Rider Home"),
  receiveRubbingDevicePageKey("Receive Rubbing Device"),
  rubbingHomePageKey("Rubbing Home"),
  deviceScannerPageKey("Device Scanner"),
  trcExecutivePageKey("Trc Executive"),
  splashPageKey("splash");

  @override
  final String value;

  const PageGroup(this.value);
}
