import 'package:csh_annotation/annotation.dart';

enum ComponentGroup with AbsComponentGroup {
  actionComponentKey("Action"),
  viewReportQcComponentKey("View Report Qc"),
  retrievedPartQcDashboardComponentKey("Retrieved Part Qc Dashboard"),
  retrievedPartsDataDetailsComponentKey("Retrieved Parts Data Details"),
  createManualShipmentComponentKey("Create Manual Shipment"),
  createShipmentComponentKey("Create Shipment"),
  uploadEwayBillComponentKey("Upload Eway Bill"),
  orderGroupDetailsComponentKey("Order Group Details"),
  subOrderGroupComponentKey("Sub Order Group List"),
  packagingProcessComponentKey("Packaging Process"),
  shipexPackingComponentKey("Packing"),
  dispatchComponentKey("Dispatch"),
  shipexHomeComponentKey("Shipex Home"),
  shipexGeneralHeaderComponentKey("Shipex General Header"),
  disputedImageCaptureComponentKey("Disputed Image Capture"),
  disputedImageBarcodeScannerComponentKey("Disputed Image Barcode Scanner"),
  calculatorMediaCaptureComponentKey("Calculator Media Capture"),
  auditBarcodeScannedComponentKey("Audit Barcode Scanner"),
  auditQuestionComponentKey("Audit Question"),
  auditQuestionSummaryComponentKey("Audit Question Summary"),
  barcodeScannerComponentKey("Barcode Qc"),
  disputedQuestionsComponentKey("Disputed Questions"),
  calculatorComponentKey("Calculator"),
  deviceReceiveComponentKey("Device Receive"),
  qcGeneralHeaderComponentKey("QC General Header"),
  qcActionComponentKey("QC Action"),
  loginComponentKey("Login"),
  trcAndQcLoginComponentKey("Trc and QC Login"),
  pendingPartDetailsComponentKey("Pending Part Details"),
  pendingDeliveryComponentKey("Pending Delivery"),
  alternatePartComponentKey("Alternate Part"),
  assignedPartDetailsComponentKey("Assigned Part Details Component"),
  assignPartBarcodeScannerComponentKey("Assign Part Barcode Scanner"),
  assignedDeviceDetailsComponentKey("Assigned device Details"),
  inventoryHomeComponentKey("Inventory Home"),
  pendingPartListComponentKey("Pending Part List"),
  returnItemStatusComponentKey("Return Item Status"),
  returnComponentKey("Return"),
  summaryComponentKey("Summary"),
  partSelectionQCComponentKey("Part Selection QC"),
  elssStatusComponentKey("Elss Status"),
  allowedOptionComponentKey("Allowed Options"),
  addPartsQcComponentKey("Add Parts QC"),
  partSelectionComponentKey("Part Selection TRC"),
  brandDetailsListingComponentKey("Brand Details Listing"),
  addPartComponentKey("ADD Part"),
  addDeviceMediaComponentKey("Add Device Media"),
  elssHomeComponentKey("Elss Home"),
  managePartsComponentKey("Manage Parts"),
  myDevicesComponentKey("My Devices"),
  wipDeviceComponentKey("WIP Devices"),
  viewReportComponentKey("View Report"),
  engineerHomeComponentKey("Engineer Home"),
  homeComponentKey("Home"),
  l4ComponentKey("L4"),
  pqStatusChangeComponentKey("PQ Status Change"),
  partQcHomeComponentKey("Part Qc Home"),
  deliveryDeliverEngineerPartsComponentKey("Delivery Deliver Engineer Parts"),
  pickUpReceiveEngineerPartsCompo("PickUp Receive Engineer Parts"),
  riderHomeComponentKey("Rider Home"),
  receiveRubbingDeviceComponentKey("Receive rubbing Device"),
  rubbingHomeComponentKey("Rubbing Home"),
  deviceScannerComponentKey("Device Scanner"),
  TRCExecutiveComponentKey("Trc executive"),
  generalHeaderComponentKey("General Header"),
  trcTesterComponentKey("Trc Tester"),
  splashComponentKey("Splash"),
  StoreIn("Store In"),
  StoreOut("Store Out"),
  StoreOutLotItemsScan("Store Out Lot Items Scan"),
  ReasonSelection("Reason Selection"),
  DeviceDead("Device Dead"),
  DeviceDeadAcceptReject("Device Dead Accept Reject"),
  trcStoreManagerHomeComponentKey("Store Manager Home Component"),
  trcRetrievedPartListComponentKey("Trc Retrieved Part List Component"),
  pendingDispatchProviderListComponentKey("Pending Dispatch Provider List Component"),
  completeDispatchComponentKey("Complete Dispatch Component");

  @override
  final String value;

  const ComponentGroup(this.value);
}

enum PageGroup with AbsPageGroup {
  actionPageKey("Action"),
  viewReportQcPageKey("View Report Qc"),
  retrievedPartQcDashboardPageKey("Retrieved Part Qc Dashboard"),
  retrievedPartsDataDetailsPageKey("Retrieved Parts Data Details"),
  createManualShipmentPageKey("Create Manual Shipment"),
  createShipmentPageKey("Create Shipment"),
  uploadEwayBillPageKey("Upload Eway Bill"),
  orderGroupDetailsPageKey("Order Group Details"),
  subOrderGroupListingKey("Sub Order Group Listing"),
  packagingProcessPageKey("Packaging Process"),
  shipexPackingPageKey("Packing"),
  dispatchPageKey("Dispatch"),
  shipexHomePageKey("Shipex Home"),
  disputedImageCapturePageKey("Disputed Image Capture"),
  disputedImageBarcodeScannerPageKey("Disputed Image Barcode Scanner"),
  calculatorMediaCapturePageKey("Calculator Media Capture"),
  auditBarcodeScannedPageKey("Audit Barcode Scanner"),
  auditQuestionPageKey("Audit Question"),
  auditQuestionSummaryPageKey("Audit Question Summary"),
  barcodeScannerPageKey("Barcode Qc"),
  disputedQuestionsPageKey("Disputed Questions"),
  calculatorPageKey("Calculator"),
  deviceReceivePageKey("Device Receive"),
  qcActionPageKey("QC Action"),
  loginPageKey("Login"),
  trcAndQcLoginPageKey("Trc and QC Login"),
  pendingPartDetailsPageKey("Pending Part Details"),
  pendingDeliveryPageKey("Pending Delivery"),
  alternatePartPageKey("Alternate Part"),
  assignedPartDetailsPageKey("Assigned Part Details Component"),
  assignPartBarcodeScannerPageKey("Assign Part Barcode Scanner"),
  assignedDeviceDetailsPageKey("Assigned device Details"),
  inventoryHomePageKey("Inventory Home"),
  pendingPartListPageKey("Pending Part List"),
  returnItemStatusPageKey("Return Item Status"),
  returnPageKey("Return"),
  summaryPageKey("Summary"),
  partSelectionQCPageKey("Part Selection QC"),
  elssStatusPageKey("Elss Status"),
  allowedOptionPageKey("Allowed Options"),
  addPartsQCPageKey("Add Parts QC"),
  partSelectionPageKey("Part Selection TRC"),
  brandDetailsListingPageKey("Brand Details Listing"),
  addPartPageKey("Add Part"),
  addDeviceMediaPageKey("Add Device Media"),
  elssHomePageKey("Elss Home"),
  managePartsPageKey("Manage Parts"),
  myDevicesPageKey("My Devices"),
  wipDevicesPageKey("WIP Devices"),
  viewReportPageKey("View Report"),
  engineerHomePageKey("Engineer Home"),
  homePageKey("Home"),
  l4PageKey("L4"),
  pqStatusChangePageKey("PQ Status Change"),
  partQcHomePageKey("Part Qc Home"),
  deliveryDeliverEngineerPartsPageKey("Delivery Deliver Engineer Parts"),
  pickUpReceiveEngineerPageKey("PickUp Receive Engineer Parts"),
  riderHomePageKey("Rider Home"),
  receiveRubbingDevicePageKey("Receive Rubbing Device"),
  rubbingHomePageKey("Rubbing Home"),
  deviceScannerPageKey("Device Scanner"),
  trcExecutivePageKey("Trc Executive"),
  trcTesterPageKey("Trc Tester"),
  splashPageKey("splash"),
  qcStoreInKey("Store In"),
  qcStoreOutKey("Store Out"),
  qcDeviceDeadRepairPageKey("Device Dead Repair"),
  qcReasonSelectionPageKey("Reason Selection"),
  qcDeviceDeadAcceptRejectPageKey("Device Dead Accept Reject"),
  trcStoreManagerHomePageKey("Trc Store Home Manager"),
  trcRetrievedPartListPageKey("Trc Retrieved Part List"),
  pendingDispatchProviderListPageKey("Pending Dispatch Provider List"),
  completeDispatchPageKey("Complete Dispatch");

  @override
  final String value;

  const PageGroup(this.value);
}
