name: flutter_trc
description: A new Flutter application.



# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.5.0+59

web_version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'
#  flutter: '<=3.22.2'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0

  calculator:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: calculator
  core:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: core

  localization:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: localization

  components:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: v2.1.2
      path: components

  core_widgets:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: v2.1.2
      path: core_widgets

  calculator_ui:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: v2.1.2
      path: calculator_ui

  ml_barcode_scanner:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: v2.1.2
      path: ml_barcode_scanner

  imei_serial_reader:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: v2.1.2
      path: imei_serial_reader

  builder_component:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: builder_component

  builder_project:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: builder_project
  csh_db:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: csh_db

  csh_annotation:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: csh_annotation

  video_optimizer:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: video_optimizer

  csh_gallery_view:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: csh_gallery_view

  device_info_plus: ^10.1.0
  alice: ^0.4.2
  connectivity_plus: ^6.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  package_info_plus: ^8.0.2
  provider: ^6.0.4
  flutter_feather_icons: ^2.0.0+1
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  lottie: ^3.1.2
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  #  open_filex: ^4.3.2
  fl_chart: ^0.68.0
  visibility_detector: ^0.4.0+2
  file_picker: ^8.0.3
  path: ^1.8.3
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  path_provider: ^2.0.15
  firebase_remote_config: ^5.0.0
  image: ^4.2.0
  url_launcher: ^6.1.12
  flutter_tts: ^4.0.2
  #  ffmpeg_kit_flutter_video: 5.1.0
  video_player: ^2.7.0
  flutter_image_compress: ^2.0.4
  firebase_crashlytics: ^4.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  disk_space: ^0.2.1
  get_storage: ^2.1.1
  local_auth: ^2.3.0
  app_settings: ^5.1.1

flutter_launcher_icons:
  android: false
  ios: true
  image_path_ios: "assets/images/app_android_icon.png"
  background_color_ios: "#ffffff"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  frontend_server_client: ^4.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

#    path: ../flutter_packages/csh_schema_generator
  csh_schema_generator:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: v2.0.9
      path: csh_schema_generator




dependency_overrides:
  build: ^2.4.1
  build_runner: ^2.4.13
  source_gen: ^1.5.0
  wakelock_plus: 1.2.5
#  source_helper: ^1.3.4
  analyzer: ^6.5.0
  meta: ^1.15.0
#  dart_style: ^2.3.6

#  source_gen: 1.2.7
  graphs: 2.2.0
  flutter_widget_from_html: ^0.15.1
  intl: ^0.19.0
  rxdart: ^0.28.0
  uuid: ^4.4.0
  #  graphs: 2.2.0
  camera: ^0.11.0+2
  camera_android_camerax: 0.6.7+2
  flutter_image_compress: ^2.0.4
  package_info_plus : ^8.0.2
#  csh_annotation:
#    path: ../flutter_packages/csh_annotation
#  builder_component:
#    path: ../flutter_packages/builder_component
#  localization:
#    path: ../flutter_packages/localization
#  core:
#    path: ../flutter_packages/core
#  calculator:
#    path: ../flutter_packages/calculator
#
#  video_optimizer:
#    path: ../flutter_packages/video_optimizer
#  components:
#    path: ../flutter_admin_ui/components
#
#  core_widgets:
#    path: ../flutter_admin_ui/core_widgets
#
#  calculator_ui:
#    path: ../flutter_admin_ui/calculator_ui
#
#  ml_barcode_scanner:
#    path: ../flutter_admin_ui/ml_barcode_scanner
#
#  imei_serial_reader:
#    path: ../flutter_admin_ui/imei_serial_reader

#  csh_annotation:
#    git:
#      url: https://github.com/reglobe/flutter_packages.git
#      ref: v2.0.9
#      path: csh_annotation
#  builder_component:
#    git:
#      url: https://github.com/reglobe/flutter_packages.git
#      ref: v2.0.9
#      path: builder_component
#  localization:
#    git:
#      url: https://github.com/reglobe/flutter_packages.git
#      ref: v2.0.9
#      path: localization
#  core:
#    git:
#      url: https://github.com/reglobe/flutter_packages.git
#      ref: v2.0.9
#      path: core
#  core_widgets:
#    git:
#      url: https://github.com/reglobe/flutter_admin_ui.git
#      ref: v2.1.2
#      path: core_widgets
#  calculator:
#    git:
#      url: https://github.com/reglobe/flutter_packages.git
#      ref: v2.0.9
#      path: calculator
  components:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: components

  core_widgets:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: core_widgets

  calculator_ui:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: calculator_ui






flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
    - assets/stage/
    - assets/beta/
    - assets/prodTest/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_semi_bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 600
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400

