name: flutter_trc
description: A new Flutter application.



# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
web_version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=1.17.1'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  core:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: master
      path: core

  localization:
    git:
      url: https://github.com/reglobe/flutter_packages.git
      ref: master
      path: localization

  components:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: components

  core_widgets:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: core_widgets

  calculator_ui:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: calculator_ui

  s3_file_uploader_interface:
    git:
      url: https://github.com/reglobe/flutter_plugins.git
      ref: prod
      path: s3_file_uploader_interface

  s3_file_uploader:

    git:
      url: https://github.com/reglobe/flutter_plugins.git
      ref: prod
      path: s3_file_uploader


  device_info_plus: ^8.1.0
  sentry_flutter: ^6.5.1
  alice: ^0.2.5
  connectivity_plus: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  package_info_plus: ^1.4.2
  provider: ^6.0.4
  flutter_feather_icons: ^2.0.0+1
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  lottie: ^2.0.0
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+3
  qr_code_scanner: ^1.0.1
  open_filex: ^4.3.2
  fl_chart: ^0.61.0
  visibility_detector: ^0.3.3
  file_picker: ^5.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0



dependency_overrides:
  permission_handler: ^10.2.0
  webview_flutter: ^3.0.4
  device_info_plus: ^8.1.0
  open_filex: ^4.3.2
  package_info_plus: ^3.0.1
  flutter_html: ^2.2.1
  file_picker: ^4.5.1
  intl: ^0.18.0
  ffi: ^2.0.1


  core_widgets:
    git:
      url: https://github.com/reglobe/flutter_admin_ui.git
      ref: main
      path: core_widgets


  visibility_detector: ^0.3.3








flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_semi_bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 600
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400


